### ISSUE TITLE
Cannot add bosun incident list to dashboard

### ISSUE THREAD

**Issue by idpwf** [bosun-monitor/bosun-grafana-app#21]
Hi,

When trying to add the incident list, I get the error 
"Plugin Error
Cannot read property 'id' of undefined"

In the browser console (Chromium on Ubuntu), this is logged:
TypeError: Cannot read property 'getElementsByTagName' of null(…)
boot.4a046b2f.js:23 Plugin component error TypeError: Cannot read property 'id' of undefined(…)
boot.4a046b2f.js:37 TypeError: datasource.IncidentListQuery is not a function
    at eval (module.js:109)
    at g (boot.4a046b2f.js:38)
    at boot.4a046b2f.js:38
    at o.$eval (boot.4a046b2f.js:38)
    at o.$digest (boot.4a046b2f.js:38)
    at boot.4a046b2f.js:38
    at f (boot.4a046b2f.js:36)
    at boot.4a046b2f.js:36

Grafana: nightly, Grafana v4.0.0-pre1 (commit: 658fc1a)
Bosun: 0.0.25

Does Grafana 4 even support Bosun now?

TIA
Micky

**Comment by kylebrandt** [comment]
Probably not. I haven't tested it yet, so not sure what breaks with Grafana
4. Should work fine with latest stable, 3.1.1 IIRC

**Comment by VJean** [comment]
Hi,
are there plans about supporting Grafana 4 ? It is currently in beta and the stable release is planned for the end of the month.

As of now, when trying the plugin (0.0.26) in Grafana 4 (beta1) :
- there's no Bosun entry in the top left menu anymore
- it seems to work as a datasource (i'm able to plot graphs based on bosun queries)
- the Incident List Panel can't be added to the dashboards. I'm getting the following errors, if it helps :
```
Plugin component error : TypeError: dashboardSrv.currentDashboard is undefined
```
```
Error: datasource.IncidentListQuery is not a function
```

Thanks !

**Comment by rohitpmore** [comment]
Hi, any updates on this?
Since, grafana 4 is now stable?

Thanks,
Rohit.

**Comment by shanky5** [comment]
hello,

Grafana 4.0.2 is stable now. Any updates on when will this get fixed?

Thanx,
Shanky

**Comment by kylebrandt** [comment]
This works fine for me in v4.1.0. What version are you all running? Maybe an older one that was impacted by this grafana issue? https://github.com/grafana/grafana/issues/6759

Please let me know if this isn't working for you in v4.1
